version: '3'
services:
    blogweb:
        build:
            context: .
            dockerfile: Dockerfile
        image: build:blog
        user: root
        volumes:
            # - ./conf/html/:/data/web/html/
            - ./deploy_conf/logs:/var/log/nginx
            - ./deploy_conf/conf.d:/etc/nginx/conf.d
        ports:
            - '7003:80'
