name: push blog

on:
    push:
        branches:
            - master

jobs:
    build:
        # runs-on 指定job任务运行所需要的虚拟机环境(必填字段)
        runs-on: ubuntu-latest
        steps:
            # 获取源码
            - name: code
              # 使用action库  actions/checkout获取源码
              uses: actions/checkout@master

            # 安装Node10
            - name: install node.js
              # 使用action库  actions/setup-node安装node
              uses: actions/setup-node@v2.5.0
              with:
                  node-version: '16.X'

            # 安装依赖
            - name: npm install
              run: npm install

            # 打包
            - name: build
              run: npm run build

            - name: copy file via ssh password
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.REMOTE_HOST }}
                  username: 'root'
                  password: ${{ secrets.REMOTE_PASS }}
                  port: 22
                  source: 'docs/'
                  target: ${{ secrets.REMOTE_TARGET }}
